server:
  port: 8763
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: order-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yizu?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml